In [1]:
import pandas as pd

In [20]:
df_total = pd.read_feather(r'F:\Projects\Pfizer_mCRPC\Data\Raw_data\02_total_with_datediff.feather')
df_HCP = pd.read_csv(r'F:\Projects\Pfizer_mCRPC\Data\Raw_data\03_Pfizer_mCRPC_HCPHCOS_WITH_DUMMIES.csv')

In [21]:
df_HCP.head()

,patient_id,hcos_mcrpc_decile,hcp_zx_decile,hcp_mcrpc_decile,hcp_agonist_pat_cnt,hcp_antagonist_pat_cnt,hcp_adt_score,hhi,pri_spcl_desc_abdominal_radiology,pri_spcl_desc_abdominal_surgery,...,cot_facility_type_physical_medicine_and_rehabilitation,cot_facility_type_psychiatric_hospital,cot_facility_type_rehabilitation_hospital,cot_facility_type_rescue,cot_facility_type_research_institute,cot_facility_type_research_laboratory,hcp_region_midwest,hcp_region_northeast,hcp_region_south,hcp_region_west
0,839544914,10.0,10.0,10,61.0,20.0,0.506173,0.528096,0,0,...,0,0,0,0,0,0,0,0,0,1
1,582866916,NaN,NaN,7,6.0,NaN,1.000000,0.781250,0,0,...,0,0,0,0,0,0,0,0,0,1
2,171011889,10.0,NaN,3,1.0,NaN,1.000000,1.000000,0,0,...,0,0,0,0,0,0,1,0,0,0
3,645101969,4.0,1.0,3,NaN,NaN,NaN,1.000000,0,0,...,0,0,0,0,0,0,0,0,0,1
4,152961559,7.0,1.0,5,1.0,NaN,1.000000,0.520000,0,0,...,0,0,0,0,0,0,0,0,1,0

In [22]:
df_total_with_dummies = df_total.merge(df_HCP, on = 'patient_id', how='inner')

In [25]:
df_total_with_dummies.head()

,patient_id,pn_flag,age_index,age_pc,c00142_claim_cnt,c00142_flag,c00142_index_max_dd,c00142_index_min_dd,c00142_max_min_dd,c00740_claim_cnt,...,cot_facility_type_physical_medicine_and_rehabilitation,cot_facility_type_psychiatric_hospital,cot_facility_type_rehabilitation_hospital,cot_facility_type_rescue,cot_facility_type_research_institute,cot_facility_type_research_laboratory,hcp_region_midwest,hcp_region_northeast,hcp_region_south,hcp_region_west
0,377317624,0,85,85,0,0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0,1,0,0
1,73066609,0,80,78,0,0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,1,0,0,0
2,70175556,0,50,50,0,0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0,1,0,0
3,713474282,0,83,81,0,0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,1,0,0,0
4,1563563420,0,70,64,0,0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0,0,1,0

In [27]:
df_total_with_dummies.to_feather(r'F:\Projects\Pfizer_mCRPC\Data\Raw_data\04_total_with_datediff_and_dummies.feather')
df_total_with_dummies.to_csv(r'F:\Projects\Pfizer_mCRPC\Data\Raw_data\04_total_with_datediff_and_dummies.csv', index=False)

In [28]:
df_total_with_dummies.head()

,patient_id,pn_flag,age_index,age_pc,c00142_claim_cnt,c00142_flag,c00142_index_max_dd,c00142_index_min_dd,c00142_max_min_dd,c00740_claim_cnt,...,cot_facility_type_physical_medicine_and_rehabilitation,cot_facility_type_psychiatric_hospital,cot_facility_type_rehabilitation_hospital,cot_facility_type_rescue,cot_facility_type_research_institute,cot_facility_type_research_laboratory,hcp_region_midwest,hcp_region_northeast,hcp_region_south,hcp_region_west
0,377317624,0,85,85,0,0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0,1,0,0
1,73066609,0,80,78,0,0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,1,0,0,0
2,70175556,0,50,50,0,0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0,1,0,0
3,713474282,0,83,81,0,0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,1,0,0,0
4,1563563420,0,70,64,0,0,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0,0,1,0

In [33]:
# Due to the repull one feature is set to 0, columns related should be deleted
ls_deleted_features = ['g214060_claim_cnt', 'g214060_flag', 'g214060_max_min_dd', 'g214060_index_max_dd', 'g214060_index_min_dd']
df_total_with_dummies.drop(ls_deleted_features, axis=1, inplace=True)

In [35]:
df_total_with_dummies.to_feather(r'F:\Projects\Pfizer_mCRPC\Data\Raw_data\04_total_with_datediff_and_dummies.feather')
df_total_with_dummies.to_csv(r'F:\Projects\Pfizer_mCRPC\Data\Raw_data\04_total_with_datediff_and_dummies.csv', index=False)

## Make version without flags

In [2]:
df_total_with_dummies = pd.read_feather(r'F:\Projects\Pfizer_mCRPC\Data\Raw_data\04_total_with_datediff_and_dummies.feather')

In [7]:
flag_columns = [colname for colname in df_total_with_dummies.columns if (colname[-4:] == 'flag') and not (colname == 'pn_flag')]

In [11]:
df_no_flags = df_total_with_dummies.drop(columns = flag_columns)

In [12]:
df_no_flags.to_feather(r'F:\Projects\Pfizer_mCRPC\Data\Raw_data\04_total_with_datediff_and_dummies_no_flags.feather')